export default class CommonConstants {

  /**
   * 组件尺寸
   */

  static readonly FULL_WIDTH = '100%';
  static readonly FULL_HEIGHT =  '100%';
  static readonly HALF_SIZE = '50%';
  static readonly CONTENT_SIZE = '90%';
  static readonly FONT_BOLDER = '700';

  /**
   * Input length of the account.
   */
  static readonly INPUT_ACCOUNT_LENGTH = 11;

  /**
   *  Input length of the password.
   */
  static readonly INPUT_PASSWORD_LENGTH = 8;

  /**
   *  Left padding of the input box
   */
  static readonly INPUT_PADDING_LEFT = 0;

  /**
   * Delay time of simulated login
   */
  static readonly LOGIN_DELAY_TIME = 2000;

  /**
   * Common Spacing of Components
   */
  static readonly COMMON_SPACE = 12;

  /**
   * Title text of the home page
   */
  static readonly HOME_TITLE = '首页';

  /**
   * Title text of the setting page
   */
  static readonly SORT_TITLE = '分类';

  static readonly MINE_TITLE = '我的';

  static readonly COMMUNITY_TITLE = "社区";


  /**
   * Spacing of other login methods
   */
  static readonly LOGIN_METHODS_SPACE = 44;

  /**
   * The width or height of the component is spread across the parent component.
   */
  static readonly FULL_PARENT = '100%';

  /**
   * The width of button
   */
  static readonly BUTTON_WIDTH = '90%';

  /**
   * Home tab index
   */
  static readonly HOME_TAB_INDEX = 0;

  /**
   * Mine tab index
   */
  static readonly SORT_TAB_INDEX = 1;

  static readonly COMMUNITY_TAB_INDEX = 2;

  static readonly MINE_TAB_INDEX = 3;

  //社区部分
  static readonly GOODS_LIST_HEIGHT: string = '20%';
  static readonly GOODS_IMAGE_WIDTH: string = '40%';
  static readonly GOODS_FONT_WIDTH: string = '60%';
  static readonly GOODS_LIST_WIDTH: string = '94%';
  static readonly LAYOUT_WIDTH_OR_HEIGHT: string = '100%';

  // font-size
  static readonly GOODS_LIST_PADDING: number = 8;
  static readonly GOODS_EVALUATE_FONT_SIZE: number = 12;
  static readonly NORMAL_FONT_SIZE: number = 16;
  static readonly BIGGER_FONT_SIZE: number = 20;
  static readonly MAX_FONT_SIZE: number = 32;

  // margin
  static readonly REFRESH_ICON_MARGIN_RIGHT: number = 20;
  static readonly MARGIN_RIGHT: number = 32;

  // width or height
  static readonly ICON_WIDTH: number = 40;
  static readonly ICON_HEIGHT: number = 40;

  // list space
  static readonly LIST_ITEM_SPACE: number = 16;

  // navigation title
  static readonly STORE: string = '社区';

  // offset range
  static readonly MAX_OFFSET_Y: number = 100;

  // refresh time
  static readonly REFRESH_TIME: number = 1500;

  // Magnification
  static readonly MAGNIFICATION: number = 2;
  static readonly MAX_DATA_LENGTH: number = 12;


  //个人页面
  /**
   * The entry ability tag.
   */
  static readonly TAG_ABILITY: string = 'EntryAbility';

  /**
   * The home page tag.
   */
  static readonly TAG_HOME: string = 'PersonalPage';

  /**
   * The Common utils tag.
   */
  static readonly TAG_COMMON_UTILS: string = 'CommonUtils';

  /**
   * Custom dialog widget tag.
   */
  static readonly TAG_CUSTOM: string = 'CustomDialogWidget';

  /**
   * Date year
   */
  static readonly DATE_YEAR: string = '年';

  /**
   * Date month
   */
  static readonly DATE_MONTH: string = '月';

  /**
   * Date day
   */
  static readonly DATE_DAY: string = '日';

  /**
   * Date dialog start time.
   */
  static readonly START_TIME: string = '1900-1-1';

  /**
   * Date dialog select time.
   */
  static readonly SELECT_TIME: string = '1990-1-1';

  /**
   * Image back margin left of the 7.2.
   */
  static readonly BACK_MARGIN_LEFT: string = '7.2%';

  /**
   * Image avatar margin top of the 5.5.
   */
  static readonly AVATAR_MARGIN_TOP: string = '5.5%';

  /**
   * Text personal margin top of the 2.1.
   */
  static readonly PERSONAL_MARGIN_TOP: string = '2.1%';

  /**
   * Common dialog width of the 93.3.
   */
  static readonly COMMON_DIALOG_WIDTH: string = '93.3%';

  /**
   * Join comma
   */
  static readonly COMMA: string = '，';

  /**
   * Image back margin top of the 19.
   */
  static readonly BACK_MARGIN_TOP: number = 19;

  /**
   * Font weight of the 500.
   */
  static readonly BIGGER: number = 500;

  /**
   * Dialog y-axis offset distance of the 20.
   */
  static readonly DY_OFFSET: number = -20;

  /**
   * Current month plus one.
   */
  static readonly PLUS_ONE: number = 1;

  /**
   * Layout weight size of the 1.
   */
  static readonly WEIGHT_ONE: number = 1;

  /**
   * Text common max lines of the 1.
   */
  static readonly ONE_LINES: number = 1;

  static readonly HOME_PAGE_COURSE_HEIGHT: string = '15%';
  static readonly HOME_PAGE_COURSE_IMG_WIDTH: string = '37%';
  static readonly HOME_PAGE_COURSE_TEXT_WIDTH: string = '63%';

}