export default class CommonConstants {

  /**
   * 组件尺寸
   */

  static readonly FULL_WIDTH = '100%';
  static readonly FULL_HEIGHT =  '100%';
  static readonly HALF_SIZE = '50%';
  static readonly CONTENT_SIZE = '90%';
  static readonly FONT_BOLDER = '700';

  /**
   * Input length of the account.
   */
  static readonly INPUT_ACCOUNT_LENGTH = 11;

  /**
   *  Input length of the password.
   */
  static readonly INPUT_PASSWORD_LENGTH = 8;

  /**
   *  Left padding of the input box
   */
  static readonly INPUT_PADDING_LEFT = 0;

  /**
   * Delay time of simulated login
   */
  static readonly LOGIN_DELAY_TIME = 2000;

  /**
   * Common Spacing of Components
   */
  static readonly COMMON_SPACE = 12;

  /**
   * Title text of the home page
   */
  static readonly HOME_TITLE = '首页';

  /**
   * Title text of the setting page
   */
  static readonly SORT_TITLE = '分类';

  static readonly MINE_TITLE = '我的';

  static readonly COMMUNITY_TITLE = "社区";


  /**
   * Spacing of other login methods
   */
  static readonly LOGIN_METHODS_SPACE = 44;

  /**
   * The width or height of the component is spread across the parent component.
   */
  static readonly FULL_PARENT = '100%';

  /**
   * The width of button
   */
  static readonly BUTTON_WIDTH = '90%';

  /**
   * Home tab index
   */
  static readonly HOME_TAB_INDEX = 0;

  /**
   * Mine tab index
   */
  static readonly SORT_TAB_INDEX = 1;

  static readonly COMMUNITY_TAB_INDEX = 2;

  static readonly MINE_TAB_INDEX = 3;

  //社区部分
  static readonly GOODS_LIST_HEIGHT: string = '20%';
  static readonly GOODS_IMAGE_WIDTH: string = '40%';
  static readonly GOODS_FONT_WIDTH: string = '60%';
  static readonly GOODS_LIST_WIDTH: string = '94%';
  static readonly LAYOUT_WIDTH_OR_HEIGHT: string = '100%';

  // font-size
  static readonly GOODS_LIST_PADDING: number = 8;
  static readonly GOODS_EVALUATE_FONT_SIZE: number = 12;
  static readonly NORMAL_FONT_SIZE: number = 16;
  static readonly BIGGER_FONT_SIZE: number = 20;
  static readonly MAX_FONT_SIZE: number = 32;

  // margin
  static readonly REFRESH_ICON_MARGIN_RIGHT: number = 20;
  static readonly MARGIN_RIGHT: number = 32;

  // width or height
  static readonly ICON_WIDTH: number = 40;
  static readonly ICON_HEIGHT: number = 40;

  // list space
  static readonly LIST_ITEM_SPACE: number = 16;

  // navigation title
  static readonly STORE: string = '社区';

  // offset range
  static readonly MAX_OFFSET_Y: number = 100;

  // refresh time
  static readonly REFRESH_TIME: number = 1500;

  // Magnification
  static readonly MAGNIFICATION: number = 2;
  static readonly MAX_DATA_LENGTH: number = 12;

  static readonly HOME_PAGE_COURSE_HEIGHT: string = '15%';
  static readonly HOME_PAGE_COURSE_IMG_WIDTH: string = '37%';
  static readonly HOME_PAGE_COURSE_TEXT_WIDTH: string = '63%';
}